[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"
authors = ["Fernando Martins <emmanuel.martins@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "aoc2022"
path = "src/lib.rs"